version: "3.7"
services:
  scrp:
    image: sfproductlabs/scrp:latest
    # command: tail -F test
    networks:
      - forenet
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:      
          - node.role != manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    logging:
      options:
          max-size: "100k"
    environment:
      - SWARM_NODE={{.Node.Hostname}}
      - CASSANDRAS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_RETRY=false
      - CASSANDRA_VERIFY_HOSTS=false
      - CASSANDRA_ROOTCA=/run/secrets/prod-rootCa.crt
      - CASSANDRA_CLIENT_CERT=/run/secrets/prod-cassandra-client.crt
      - CASSANDRA_CLIENT_KEY=/run/secrets/prod-cassandra-client.key
      - BACKEND_CERT=
      - BACKEND_KEY=
      - CLUSTER_ENDPOINT=scrp_scrp:50551
    secrets:
      - prod-cassandra-client.crt
      - prod-cassandra-client.key
      - prod-rootCa.crt

secrets:
  prod-cassandra-client.crt:
    external: true
  prod-cassandra-client.key:
    external: true
  prod-rootCa.crt:
    external: true

networks:
  forenet:
    external: true          